; Ядро плагина
rt_core.amxx

; Минирование
rt_planting.amxx
; Ограничения
rt_restrictions.amxx
; Линия прогресса при воскреш./минировании
rt_timer.amxx
; Эффекты
rt_effects.amxx
; Звуки
rt_sounds.amxx
; Бонусы за воскреш./минирования
rt_bonus.amxx
; Модель при воскрешении
rt_revive_model.amxx