custom_player_models_api.amxx ; Ядро плагина

; Modules should be placed below than core plguin/Модули должны располагаться ниже основного плагина
custom_player_models_cfg.amxx ; Изменение моделей игроков
custom_player_models_toggle.amxx ; Позволит скрыть модели игроков командой /models