; Admin Base - Always one has to be activated
admin.amxx
;admin_sql.amxx
admincmd.amxx
;adminhelp.amxx	
adminslots.amxx
;multilingual.amxx	
; Menus
menufront.amxx		; front-end for admin menus
cmdmenu.amxx		; command menu (speech, settings)
plmenu.amxx		; players menu (kick, ban, client cmds.)
;telemenu.amxx		; teleport menu (Fun Module required!)
mapsmenu.amxx		; maps menu (vote, changelevel)
pluginmenu.amxx		; Menus for commands/cvars organized by plugin

; Chat / Messages
adminchat.amxx		; console chat commands
antiflood.amxx		; prevent clients from chat-flooding the server
;scrollmsg.amxx		; displays a scrolling message
;imessage.amxx		; displays information messages
adminvote.amxx		; vote commands

; Map related
;nextmap.amxx		; displays next map in mapcycle
;mapchooser.amxx		; allows to vote for next map
;timeleft.amxx		; displays time left on map

; Configuration
pausecfg.amxx		; allows to pause and unpause some plugins
statscfg.amxx		; allows to manage stats plugins via menu and commands

; Counter-Strike
;restmenu.amxx		; restrict weapons menu
statsx.amxx		; stats on death or round end (CSX Module required!)
;miscstats.amxx		; bunch of events announcement for Counter-Strike
;stats_logging.amxx	; weapons stats logging (CSX Module required!)

csstatsx_sql.amxx
aes_statsx_cstrike.amxx
aes_main.amxx
aes_informer.amxx
aes_exp_editor.amxx
aes_exp_cstrike.amxx
aes_bonus_system.amxx
aes_bonus_cstrike.amxx
map_manager_core.amxx
chatmanager.amxx
chatmanager_addon.amxx
reapi_parachute_mute.amxx
lite_auto_restart.amxx
Server-Side_SmokeNade.amxx
mute_menu.amxx
resetscore.amxx
time_for_info.amxx
mode.amxx
vip.amxx
gm_vip_test.amxx
weapons_skins_manager.amxx
ad_manager.amxx
re_gamename.amxx
healthnade.amxx
auto_team_balance_advanced.amxx
top_round_damage.amxx
round_damage_info.amxx
simple_damager.amxx
SpectatorBot.amxx
custom_player_models_api.amxx
custom_player_models_cfg.amxx
custom_player_models_toggle.amxx
no_team_flash.amxx
FirstPlayersRespawn.amxx
newkickmenu.amxx
plugins_core.amxx
molotov_grenade.amxx
block_radiocmd.amxx
awp_limiter.amxx
awp_limiter_disabled_maps.amxx
afk_control.amxx
reapi_block_FITH.amxx
round_damage_info.amxx
